StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{62E02A69AB488ADD}" {
   Id "flabby_DynamicMessage"
   Target_en_us "Suppressed sound to %1%"
   Target_en_us_edited ""
   Target_fr_fr "Son réduit à %1%."
   Target_it_it "Suono attenuato al %1%."
   Target_de_de "Geräusch auf %1% reduziert."
   Target_es_es "Sonido reducido al %1%."
   Target_cs_cz "Zvuk potlačen na %1%."
   Target_pl_pl "Dźwięk wyciszony do %1%."
   Target_ru_ru "Звук приглушен до %1%."
   Target_ja_jp "音を%1%に抑制。(Oto o %1% ni yokusei.)"
   Target_ko_kr "소리를 %1%로 억제. (Sorireul %1%ro eokje.)"
   Target_pt_br "Som suprimido para %1%."
   Target_zh_cn "声音抑制到%1%。(Shēngyīn yìzhì dào %1%.)"
   Target_uk_ua "Звук приглушено до %1%."
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1658858476
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62E02A69AF985A12}" {
   Id "flabby_KeyBindDesc"
   Target_en_us "Earplug Increase Suppression by 25%"
   Target_en_us_edited ""
   Target_fr_fr "Protection auditive : suppression augmentée de 25 %."
   Target_it_it "Tappi per le orecchie: soppressione aumentata del 25%."
   Target_de_de "Gehörschutz erhöht die Dämpfung um 25 %."
   Target_es_es "Tapones para los oídos: supresión aumentada en un 25 %."
   Target_cs_cz "Chrániče sluchu: potlačení zvýšeno o 25 %."
   Target_pl_pl "Zatyczki do uszu zwiększają tłumienie o 25%."
   Target_ru_ru "Беруши увеличивают подавление на 25 %."
   Target_ja_jp "耳栓: 抑制を25%増加 (Mimisen: yokusei o 25% zōka)"
   Target_ko_kr "귀마개로 억제 효과가 25% 증가 (Gwigmae-ro eokje hyogwa-ga 25% jeungga)"
   Target_pt_br "Tampão de ouvido aumenta a supressão em 25%."
   Target_zh_cn "耳塞：抑制提高25%。(Ěrsāi: yìzhì tígāo 25%.)"
   Target_uk_ua "Беруші збільшують придушення на 25 %."
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1658858476
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
 }
}